icetea1 : "https://zgbwcicet7001.jupiter.bbc.co.uk/"
icetea2 : "https://zgbwcicet7002.jupiter.bbc.co.uk/"
unlockicetea1 : "https://zgbwcicet7001.jupiter.bbc.co.uk/api/release_all_locks"
unlockicetea2 : "https://zgbwcicet7002.jupiter.bbc.co.uk/api/release_all_locks"
iceteaurl : "https://zgbwcicet700"
username : "ogunbo02"
fullname : "Olu Ogunbusola"
password : "password"
wrongpassword : "wrongpassword"
pause : "1.2"
wait : "5"
browser : "chrome"
debug : false
testrail : true
